language: node_js
notifications:
  email: false
node_js:
  - '10'
  - '12'
script:
  - npm run build
jobs:
  include:
    - stage: release
      node_js: '12'
      script:
        - npm run build
      after_success:
        - npm run report-coverage
        - npm run semantic-release
